import os
import sys
import logging
from logging.handlers import TimedRotatingFileHandler
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)
from read_pptx import ReadPptx
import asyncio
import openai
from dotenv import load_dotenv
import json
import aiofiles

log_dir = 'logs/explainer'
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
log_handler = TimedRotatingFileHandler(f"{log_dir}/explainer.log", when="midnight", interval=1, backupCount=5)
log_handler.suffix = "%Y%m%d"
logging.basicConfig(level=logging.INFO, handlers=[log_handler])
logger = logging.getLogger("explainer")

load_dotenv()
openai.api_key = os.getenv('OPENAI_API_KEY')
PROMPT = os.getenv('OPENAI_PROMPT')

UPLOAD_FOLDER = 'server/uploads'
RESULTS_FOLDER = 'server/results'

if not os.path.exists(RESULTS_FOLDER):
    os.makedirs(RESULTS_FOLDER)

async def process_file(file_path):
    """
    Process a PowerPoint file by extracting text from slides and generating explanations for each slide using GPT.

    Args:
        file_path (str): Path to the PowerPoint file to be processed.

    Returns:
        str: Path to the JSON file where explanations are saved.
    """
    logger.info(f"Processing file: {file_path}")
    reader = ReadPptx(file_path)
    slides_text = reader.extract_text_from_pptx_file()
    logger.info(f"Extracted text from slides: {slides_text}")

    tasks = [get_explanation_from_gpt(slide) for slide in slides_text]
    explanations = await asyncio.gather(*tasks)
    logger.info(f"Received explanations: {explanations}")
    
    slides_explanation = []
    extract_explanations(slides_explanation, explanations)

    # Extract the UID from the original filename
    uid = os.path.basename(file_path).split('_')[0]
    result_path = os.path.join(RESULTS_FOLDER, f"{uid}.json")
    await save_explanations_to_json(slides_explanation, result_path)
    logger.info(f"Saved result to: {result_path}")
    return result_path

async def get_explanation_from_gpt(text):
    """
    Fetch an explanation for the given text from GPT-3.5.

    Args:
        text (str): The text extracted from a PowerPoint slide.

    Returns:
        str: The explanation generated by GPT-3.5 for the given text, or an error message if the request fails.
    """
    prompt = f"{PROMPT} {text}"
    logger.info(f"Requesting explanation for text: {text}")
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}], timeout=10
        )
        explanation = response.choices[0].message.content
        logger.info(f"Received explanation: {explanation}")
        return explanation
    
    except openai.APIError as e:
        logger.error(f"OpenAI API returned an API Error: {e}")
        return f"OpenAI API returned an API Error: {e}"
    except openai.APIConnectionError as e:
        logger.error(f"Failed to connect to OpenAI API: {e}")
        return f"Failed to connect to OpenAI API: {e}"
    except Exception as e:
        logger.error(f"Error: {str(e)}")
        return f"Error: {str(e)}"
    
# Function that will extract explanations and return them by slide number
def extract_explanations(slides_explanation, res):
    """
    Extracts explanations and associates them with slide numbers.

    Args:
        slides_explanation (list): The list to store slide explanations.
        res (list): The list of explanations returned by GPT-3.5.
    """
    for slide_number, api_slide_explanation in enumerate(res, start=1):
        slides_explanation.append({"slide_number": slide_number, "explanation": api_slide_explanation})
        

async def save_explanations_to_json(explanations, output_path):
    """
    Saves the explanations to a JSON file.

    Args:
        explanations (list): The list of explanations to be saved.
        output_path (str): The path to the output JSON file.
    """
    async with aiofiles.open(output_path, mode='w') as f:
        await f.write(json.dumps(explanations, indent=4))
    logger.info(f"Explanations saved to {output_path}")
